### ISSUE TITLE
Error upon installation using pip3 in ubuntu

### ISSUE THREAD

**Issue by jurquiza** [Edinburgh-Genome-Foundry/icebreaker#1]
Collecting icebreaker
  Using cached https://files.pythonhosted.org/packages/25/08/7314036da8dc8df7f497756bb515bac4b635d37dcb66e71396cbc6240663/icebreaker-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5zkgge4a/icebreaker/setup.py", line 13, in <module>
        long_description=open('README.rst').read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 5301: ordinal not in range(128)

**Comment by Zulko** [comment]
Hey sorry for that, must have been because of the "¢" character in the README. I fixed it on Github. You can install from Github with:

```
pip3 install git+git://github.com/Edinburgh-Genome-Foundry/icebreaker.git
```

**Comment by Zulko** [comment]
I pushed the fix to PyPI. Closing this for now but let me know if the problem persists.
